### ISSUE TITLE
Indicate cover-to-cover indexed status

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#577] opened 2023-01-14 20:00 UTC
Currently, the only way to see if an issue has been indexed cover-to-cover is to edit the issue and then look at the comparison view to see how many pages have been indexed relative to the total page count.

Surface the total indexed page count -- or some other indication of cover-to-cover indexing complete -- in the display of the fields for the issue to make this more obvious.

**Comment by gcd-github** [comment] 2023-01-14 20:52
Excellent idea.

- Don Milne

**Comment by jochengcd** [comment] 2024-07-13 16:04
duplicate of #65

**Closed by jochengcd** 2024-07-13 16:04 UTC
