### ISSUE TITLE
Bug 680: issue reordering/moving in case of deleted issues fails

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#185] opened 2016-10-30 20:59 UTC
Originally Opened: 2011-07-21 23:21 PST

I've had no problem reordering variants, and thanks for getting the names in there Jochen.

But now I'm trying to reorder the variants for Red Sonja 14 (Dynamite series). I've done other issues from this series with no problem.

The Mel Rubi and Claudio Castellini variants are in the wrong order.  I change the number, hit preview and that's all fine but when I go to commit it throws an internal server error.  Tried it 3 or 4 times over the last 3 or 4 hours and it won't work. 

I just successfully reordered the variants for another issue in this same title and had no problems, it seems to be localized to issue 14.

**------- Comment 1 From Jochen G. 2011-07-22 00:40:52 PST -------**
What is the last issue for which you did a reordering before this one ?

**------- Comment 2 From Mike Nielsen 2011-07-22 00:56:40 PST -------**
You would ask that.  12 maybe.  I really don't remember exactly but it would have been between 9 and 13.  It worked fine whichever one it was.

And I've done other series with no problem since you fixed that other bug I found.

I'm really not trying to break it.  :)

**------- Comment 3 From Jochen G. 2011-07-22 01:56:28 PST -------**
Fixed for this one series.

We can get problems since deleted issues keep their sort_code, but the sort_code seemingly needs to be unique inside a series. So the reorder function might want to set a sort_code which we already have for a deleted issue.

Not sure what is the best way to fix. Sort_code is internal, so we might want to check for deleted ones while setting them and just skip these ? Using some high numbers for sort_codes of deleted issues is only some sort of workaround (but might be easier), it would normally avoid this problem, but in theory it could still happen.

**------- Comment 4 From Mike Nielsen 2011-07-22 19:00:18 PST -------**
Thanks Jochen.

I think your workaround sounds like a good stop-gap step.

Can the sort code go negative?  Maybe deleted ones can be given a negative sort code and then the display just ignore negative ones?  Just a thought.

**------- Comment 5 From Jochen G. 2012-10-12 21:03:47 PST -------**
**\* Bug 762 has been marked as a duplicate of this bug. ***

**------- Comment 6 From Jochen G. 2012-11-22 10:42:30 PST -------**
**\* Bug 772 has been marked as a duplicate of this bug. ***

**------- Comment 7 From Donald Dale Milne 2012-11-22 14:22:39 PST -------**
I'm surprised this (as reported in bug 772) may have something to do with deleted issues, because I ran the same sort last week immediately after deleting issues and it worked.  Only one change to issues was made between that sort episode and this attempt, which was to add one issue.

**------- Comment 8 From Jochen G. 2012-11-22 18:12:02 PST -------**
depends strongly on the series and the actual situation. Most of the time it doesn't matter. 

Happens rarely, and is difficult to fix. So for now I'll fix it by hand (will do it later for the series where you observed it)

**------- Comment 9 From Jochen G. 2013-02-07 17:39:30 PST -------**
**\* Bug 787 has been marked as a duplicate of this bug. ***

**------- Comment 10 From Jochen G. 2013-08-04 10:44:45 PST -------**
**\* Bug 815 has been marked as a duplicate of this bug. ***

**------- Comment 11 From Jochen G. 2013-10-24 07:24:44 PST -------**
**\* Bug 825 has been marked as a duplicate of this bug. ***

**------- Comment 12 From Jochen G. 2015-03-25 08:33:41 PST -------**
**\* Bug 862 has been marked as a duplicate of this bug. ***

**Comment by bookcats** [comment] 2016-11-06 12:46
Duplicate of #103 and I think that one has more in depth discussion

**Closed by bookcats** 2016-11-06 12:46 UTC
