### ISSUE TITLE
Bug 767: Voting app doesn't show details on tied vote

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#214] opened 2016-10-30 22:04 UTC
Originally Opened: 2012-11-02 22:00 PST

When the voting app records a tie vote, it produces an "invalid result".

The result should not be invalid--a tie vote implies the motion failed (because it didn't pass).

The normal list detailing who voted for each option, and who didn't vote, should also be displayed even if the result was a tie.

**Comment by bookcats** [comment] 2016-11-06 11:40
Duplicate of #126

**Closed by bookcats** 2016-11-06 11:40 UTC
Labels: bug, voting
